name = "SeticoreCapnp"
uuid = "5f96b823-c651-45d3-b54e-600e338e6562"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.6.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Conda = "1.9.0"
OrderedCollections = "1.6.2"
PyCall = "1.96.1"
